#!/bin/sh

#LAUNCHERS
$HOME/.config/bspwm/autostart.sh

bspc rule -r "*"

#fix for moving spotify to specific workspace
#bspc config external_rules_command ~/.config/bspwm/scripts/external_rules_command

# fix java apps risizing and menus - for example Arduino IDE
# first install wmname with: sudo pacman -S wmname
wmname LG3D

#BSPWM configuration
bspc config border_width         2
bspc config window_gap           5
bspc config top_padding          25
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0
bspc config single_monocle       false
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#BSPWM coloring
bspc config normal_border_color		"#c0caf5"
bspc config active_border_color		"#7aa3f7"
bspc config focused_border_color	"#bb9af7"
bspc config presel_feedback_color	"#ff9e64"
#bspc config urgent_border_color 	"#dd2727"

#Dual monitor
#find out names with arandr or xrandr
bspc monitor ${monitor} -n "$name" -d 1 2 3 4 5 6 7 8 9


bspc rule -a Oblogout state=floating
bspc rule -a gimp state=floating center=true
#Scratchpads
bspc rule -a term state=floating center=true 
bspc rule -a sptScratch state=floating center=true 
bspc rule -a scratchTerm state=floating sticky=on center=true
bspc rule -a gnome-calculator state=floating sticky=on center=true
bspc rule -a ranger state=floating center=true 
bspc rule -a Bitwarden state=floating center=true 
bspc rule -a pulse state=floating center=true 
bspc rule -a bpytop state=floating rectangle=1400x800+0+0 center=true 
bspc rule -a filezillaEdit state=floating rectangle=1800x1000+0+0 center=true 
bspc rule -a gnome-calendar state=floating center=true 
bspc rule -a TelegramDesktop state=floating rectangle=1400x800+0+0 center=true 
bspc rule -a Zulip state=floating rectangle=1400x800+0+0 center=true 
bspc rule -a 'Syncthing GTK' state=floating rectangle=1400x800+0+0 center=true 
bspc rule -a scratchpad sticky=on state=floating hidden=off

#Send specific window to specific desktop
bspc rule -a obsidian desktop='9' follow=on
bspc rule -a FileZilla desktop='5' follow=on
bspc rule -a Anydesk desktop='7' follow=on
bspc rule -a Postman desktop='6' follow=on
bspc rule -a Local desktop='15' follow=on
